# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: python:3.9
before_script:
- python --version
- pip install -r requirements.txt

stages:
- Static Analysis
- deploy

flake8:
  allow_failure: true
  stage: Static Analysis
  script:
  - pip install flake8
  - flake8 --max-line-length=120 ./papercli/*.py

pylint:
  allow_failure: true
  stage: Static Analysis
  script:
  - pip install pylint
  - pylint ./papercli/*.py

sast:
  stage: Static Analysis
include:
- template: Security/SAST.gitlab-ci.yml

deploy:
  stage: deploy
  script:
  - pip install --upgrade setuptools
  - pip install build
  - python -m build
  artifacts:
    paths:
    - dist
