name: Run unittests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5.x, 3.7.x, 3.8.x, 3.10.x]
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install required packages
        run: |
          pip install -r requirements.txt
          pip install -r dev_requirements.txt

      - name: Test
        working-directory: ./tests
        run: python3 unittests.py
